// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stronghold.EnterpriseEstimating.Data;

#nullable disable

namespace Stronghold.EnterpriseEstimating.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327183641_AddScenarioAndLostNotes")]
    partial class AddScenarioAndLostNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBook", b =>
                {
                    b.Property<int>("CostBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostBookId"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostBookId");

                    b.ToTable("CostBooks");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookEquipmentRate", b =>
                {
                    b.Property<int>("CostBookEquipmentRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostBookEquipmentRateId"));

                    b.Property<int>("CostBookId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Daily")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Hourly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Monthly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weekly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CostBookEquipmentRateId");

                    b.HasIndex("CostBookId");

                    b.ToTable("CostBookEquipmentRates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookExpense", b =>
                {
                    b.Property<int>("CostBookExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostBookExpenseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CostBookId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CostBookExpenseId");

                    b.HasIndex("CostBookId");

                    b.ToTable("CostBookExpenses");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookLaborRate", b =>
                {
                    b.Property<int>("CostBookLaborRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostBookLaborRateId"));

                    b.Property<int>("CostBookId")
                        .HasColumnType("int");

                    b.Property<string>("CraftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("StRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CostBookLaborRateId");

                    b.HasIndex("CostBookId");

                    b.ToTable("CostBookLaborRates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookOverheadItem", b =>
                {
                    b.Property<int>("CostBookOverheadItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostBookOverheadItemId"));

                    b.Property<string>("BurdenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CostBookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("CostBookOverheadItemId");

                    b.HasIndex("CostBookId");

                    b.ToTable("CostBookOverheadItems");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CrewTemplate", b =>
                {
                    b.Property<int>("CrewTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewTemplateId"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CrewTemplateId");

                    b.ToTable("CrewTemplates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CrewTemplateRow", b =>
                {
                    b.Property<int>("CrewTemplateRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewTemplateRowId"));

                    b.Property<string>("CraftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrewTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CrewTemplateRowId");

                    b.HasIndex("CrewTemplateId");

                    b.ToTable("CrewTemplateRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EquipmentRow", b =>
                {
                    b.Property<int>("EquipmentRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentRowId"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EquipmentRowId");

                    b.HasIndex("EstimateId");

                    b.ToTable("EquipmentRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Estimate", b =>
                {
                    b.Property<int>("EstimateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimateId"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ConfidencePct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("DtWeekends")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstimateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("HoursPerShift")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsScenario")
                        .HasColumnType("bit");

                    b.Property<string>("JobLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LostNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LostReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MsaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OtMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffingPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstimateId");

                    b.HasIndex("StaffingPlanId");

                    b.HasIndex("CompanyCode", "EstimateNumber")
                        .IsUnique();

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EstimateRevision", b =>
                {
                    b.Property<int>("EstimateRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimateRevisionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipCount")
                        .HasColumnType("int");

                    b.Property<decimal>("EquipTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("LaborCount")
                        .HasColumnType("int");

                    b.Property<decimal>("LaborTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SavedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstimateRevisionId");

                    b.HasIndex("EstimateId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("EstimateRevisions");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EstimateSequence", b =>
                {
                    b.Property<int>("EstimateSequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimateSequenceId"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.Property<string>("SequenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EstimateSequenceId");

                    b.HasIndex("CompanyCode", "Year", "SequenceType")
                        .IsUnique();

                    b.ToTable("EstimateSequences");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EstimateSummary", b =>
                {
                    b.Property<int>("EstimateSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimateSummaryId"));

                    b.Property<decimal>("BillSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossMarginPct")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("GrossProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InternalCostTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EstimateSummaryId");

                    b.HasIndex("EstimateId")
                        .IsUnique();

                    b.ToTable("EstimateSummaries");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.ExpenseRow", b =>
                {
                    b.Property<int>("ExpenseRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseRowId"));

                    b.Property<bool>("Billable")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysOrQty")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<int>("People")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseRowId");

                    b.HasIndex("EstimateId");

                    b.ToTable("ExpenseRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.FcoEntry", b =>
                {
                    b.Property<int>("FcoEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcoEntryId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DollarAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FcoEntryId");

                    b.HasIndex("EstimateId");

                    b.ToTable("FcoEntries");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.LaborRow", b =>
                {
                    b.Property<int>("LaborRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaborRowId"));

                    b.Property<decimal>("BillDtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BillOtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BillStRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CraftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DtHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EstimateId")
                        .HasColumnType("int");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("StHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LaborRowId");

                    b.HasIndex("EstimateId");

                    b.ToTable("LaborRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBook", b =>
                {
                    b.Property<int>("RateBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateBookId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStandardBaseline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateBookId");

                    b.ToTable("RateBooks");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookEquipmentRate", b =>
                {
                    b.Property<int>("RateBookEquipmentRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateBookEquipmentRateId"));

                    b.Property<decimal?>("Daily")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Hourly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Monthly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RateBookId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weekly")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("RateBookEquipmentRateId");

                    b.HasIndex("RateBookId");

                    b.ToTable("RateBookEquipmentRates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookExpenseItem", b =>
                {
                    b.Property<int>("RateBookExpenseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateBookExpenseItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RateBookId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateBookExpenseItemId");

                    b.HasIndex("RateBookId");

                    b.ToTable("RateBookExpenseItems");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookLaborRate", b =>
                {
                    b.Property<int>("RateBookLaborRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateBookLaborRateId"));

                    b.Property<string>("CraftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RateBookId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("StRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("RateBookLaborRateId");

                    b.HasIndex("RateBookId");

                    b.ToTable("RateBookLaborRates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SettingsId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.StaffingLaborRow", b =>
                {
                    b.Property<int>("StaffingLaborRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffingLaborRowId"));

                    b.Property<string>("CraftCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DtHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LaborType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NavCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OtRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("StHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("StRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StaffingPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StaffingLaborRowId");

                    b.HasIndex("StaffingPlanId");

                    b.ToTable("StaffingLaborRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.StaffingPlan", b =>
                {
                    b.Property<int>("StaffingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffingPlanId"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ConvertedEstimateId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<bool>("DtWeekends")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HoursPerShift")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OtMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RoughLaborTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffingPlanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffingPlanId");

                    b.HasIndex("ConvertedEstimateId");

                    b.HasIndex("CompanyCode", "StaffingPlanNumber")
                        .IsUnique();

                    b.ToTable("StaffingPlans");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.UserProfileSettings", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookEquipmentRate", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.CostBook", "CostBook")
                        .WithMany("EquipmentRates")
                        .HasForeignKey("CostBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookExpense", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.CostBook", "CostBook")
                        .WithMany("Expenses")
                        .HasForeignKey("CostBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookLaborRate", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.CostBook", "CostBook")
                        .WithMany("LaborRates")
                        .HasForeignKey("CostBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBookOverheadItem", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.CostBook", "CostBook")
                        .WithMany("OverheadItems")
                        .HasForeignKey("CostBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CrewTemplateRow", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.CrewTemplate", "CrewTemplate")
                        .WithMany("Rows")
                        .HasForeignKey("CrewTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrewTemplate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EquipmentRow", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithMany("EquipmentRows")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Estimate", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.StaffingPlan", "StaffingPlan")
                        .WithMany("Estimates")
                        .HasForeignKey("StaffingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StaffingPlan");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EstimateRevision", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithMany("Revisions")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.EstimateSummary", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithOne("Summary")
                        .HasForeignKey("Stronghold.EnterpriseEstimating.Data.Models.EstimateSummary", "EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.ExpenseRow", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithMany("ExpenseRows")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.FcoEntry", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithMany("FcoEntries")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.LaborRow", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "Estimate")
                        .WithMany("LaborRows")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookEquipmentRate", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.RateBook", "RateBook")
                        .WithMany("EquipmentRates")
                        .HasForeignKey("RateBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookExpenseItem", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.RateBook", "RateBook")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("RateBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBookLaborRate", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.RateBook", "RateBook")
                        .WithMany("LaborRates")
                        .HasForeignKey("RateBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateBook");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RolePermission", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.StaffingLaborRow", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.StaffingPlan", "StaffingPlan")
                        .WithMany("LaborRows")
                        .HasForeignKey("StaffingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StaffingPlan");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.StaffingPlan", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Estimate", "ConvertedEstimate")
                        .WithMany()
                        .HasForeignKey("ConvertedEstimateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConvertedEstimate");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.UserProfileSettings", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Stronghold.EnterpriseEstimating.Data.Models.UserProfileSettings", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.UserRole", b =>
                {
                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stronghold.EnterpriseEstimating.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CostBook", b =>
                {
                    b.Navigation("EquipmentRates");

                    b.Navigation("Expenses");

                    b.Navigation("LaborRates");

                    b.Navigation("OverheadItems");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.CrewTemplate", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Estimate", b =>
                {
                    b.Navigation("EquipmentRows");

                    b.Navigation("ExpenseRows");

                    b.Navigation("FcoEntries");

                    b.Navigation("LaborRows");

                    b.Navigation("Revisions");

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.RateBook", b =>
                {
                    b.Navigation("EquipmentRates");

                    b.Navigation("ExpenseItems");

                    b.Navigation("LaborRates");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.StaffingPlan", b =>
                {
                    b.Navigation("Estimates");

                    b.Navigation("LaborRows");
                });

            modelBuilder.Entity("Stronghold.EnterpriseEstimating.Data.Models.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
